### ISSUE TITLE
missing users db

### ISSUE THREAD

**Issue by Theolodewijk** [ghalambaz/rememberme#2]
I am missing users db

**Comment by ghalambaz** [comment]
create a table **tbl_user** for your **users**  with **username** column!
is also configurable to change that names

**Comment by Theolodewijk** [comment]
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'field list' in /home/namename/domains/namename.nl/conf/vendor/ghalambaz/remember-me/RememberMe/RememberMe.php:235 Stack trace: #0 /home/namename/domains/namename.nl/conf/vendor/ghalambaz/remember-me/RememberMe/RememberMe.php(235): PDO->prepare('SELECT id FROM ...') #1 /home/namename/domains/namename.nl/conf/vendor/ghalambaz/remember-me/RememberMe/RememberMe.php(123): RememberMe\RememberMe->getUserKey() #2 /home/namename/domains/namename.nl/public_html/themes/namename/users/index.php(15): RememberMe\RememberMe->start() #3 /home/namename/domains/namename.nl/public_html/themes/namename/users/index.php(4): persist(Object(RememberMe\Properties), 'Theo Lodewijk') #4 /home/namename/domains/namename.nl/public_html/index.php(36): include('/home/theolodew...') #5 {main} thrown in /home/namename/domains/namename.nl/conf/vendor/ghalambaz/remember-me/RememberMe/RememberMe.php on line 235

**Comment by Theolodewijk** [comment]
in te file properties.php you doing a lot with your users db so that's the reason for question for your example users table

**Comment by ghalambaz** [comment]
you are right . i made a mistake. i add example for creating tbl_users

**Comment by Theolodewijk** [comment]
nice thanks, 

here some changes if you like.

-> $properties->setTableUsers("tbl_users"); // table name that you already save your users data
-> $properties->setTableUsers("tbl_acl_users"); // table name that you already save your users data

SLQ coms with a error wehen inport, here is my example:

CREATE TABLE `tbl_acl_autologin` (
  `id` int(10) UNSIGNED NOT NULL,
  `token` char(32) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data` text NOT NULL,
  `used` int(1) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `tbl_acl_sessions` (
  `sid` varchar(40) NOT NULL,
  `expiry` int(10) UNSIGNED NOT NULL,
  `data` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

CREATE TABLE `tbl_acl_users` (
  `id` int(10) NOT NULL,
  `uuid` binary(36) NOT NULL,
  `username` char(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `email` char(100) NOT NULL,
  `mobile` bigint(30) NOT NULL,
  `created` datetime NOT NULL,
  `touched` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `img` varchar(100) NOT NULL,
  `status` enum('pending','block','delete','active') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `tbl_acl_autologin`
  ADD PRIMARY KEY (`id`,`token`) USING BTREE;

ALTER TABLE `tbl_acl_sessions`
  ADD PRIMARY KEY (`sid`) USING BTREE;

ALTER TABLE `tbl_acl_users`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `tbl_acl_users`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT;
COMMIT;

**Comment by ghalambaz** [comment]
great! thanks
